# Generated by Django 3.0.8 on 2020-08-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='created_by',
        ),
    ]
