# Generated by Django 3.0.8 on 2020-08-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200814_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(default='name', max_length=77),
        ),
    ]
