# Generated by Django 3.0.8 on 2020-08-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200816_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listing',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='catalog',
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(),
        ),
    ]
